- name: Install and configure containerd
  hosts: all
  become: true

  tasks:
    - name: Install required packages
      apt:
        name:
          - containerd
        state: present
        update_cache: true

    - name: Create containerd config directory
      file:
        path: /etc/containerd
        state: directory
        mode: "0755"

    - name: Generate default containerd config
      command: containerd config default
      register: containerd_config
      changed_when: false

    - name: Write containerd config to file
      copy:
        dest: /etc/containerd/config.toml
        content: "{{ containerd_config.stdout }}"
        mode: "0644"

    - name: Use systemd cgroup driver
      replace:
        path: /etc/containerd/config.toml
        regexp: "SystemdCgroup = false"
        replace: "SystemdCgroup = true"

    - name: Restart containerd
      systemd:
        name: containerd
        enabled: true
        state: restarted
