Vagrant.configure("2") do |config|
  nodes = {
    "cp" => {
      :hostname => "k8s-control-plane",
      :ip => "192.168.56.10",
      :memory => 2048,
      :cpus => 2
    },
    "w1" => {
      :hostname => "k8s-worker-1",
      :ip => "192.168.56.11",
      :memory => 2048,
      :cpus => 2
    },
    "w2" => {
      :hostname => "k8s-worker-2",
      :ip => "192.168.56.12",
      :memory => 2048,
      :cpus => 2
    }
  }

  config.vm.box = "ubuntu/jammy64"

  nodes.each do |name, opts|
    config.vm.define name do |node|
      node.vm.hostname = opts[:hostname]
      node.vm.network "private_network", 
        ip: opts[:ip],
        mac: "auto"
      node.vm.provider "virtualbox" do |vb|
        vb.name = opts[:hostname]
        vb.memory = opts[:memory]
        vb.cpus = opts[:cpus]
      end
    end
  end
end
