- name: Reset kubeadm
  command: kubeadm reset -f
  ignore_errors: yes

- name: Remove /etc/kubernetes directory
  file:
    path: /etc/kubernetes
    state: absent
  ignore_errors: yes

- name: Remove CNI directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/cni/net.d
    - /var/lib/cni
  ignore_errors: yes

- name: Remove kubeconfig files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /root/.kube/config
    - /home/vagrant/.kube/config
  ignore_errors: yes
