- name: Install wget, curl, vim, openssl, git
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Apache2
      ansible.builtin.apt:
        pkg:
          - wget
          - curl
          - vim
          - openssl
          - git
