- name: Set MAC address facts on each node
  hosts: all
  gather_facts: yes
  become: false

  tasks:
    #    - name: Print ansible_facts
    #      debug:
    #        var: ansible_facts
    - name: Set my_mac from default IPv4
      set_fact:
        mac_address: "{{ my_mac_list | default([]) + [ansible_facts['enp0s8']['macaddress']] }}"
    - name: Print my_mac_list
      debug:
        var: mac_address
- name: Collect MACs and detect duplicates
  hosts: all
  tasks:
    - name: Collect all Macs from hosts
      set_fact:
        mac_list: "{{ groups['all'] | map('extract', hostvars, 'mac_address') | list }}"
      run_once: true
    - name: Fail if duplicates exist
      fail:
        msg: "❗ Duplicate MAC addresses detected: {{ mac_list }}"
      when: mac_list | length != (mac_list | unique | length)

    #    - name: Check if the mac addresses are duplicated
    #      ansible.builtin.assert:
    #        that:
    #          - ( my_mac_list | length ) == ( my_mac_list | unique | length )
