- name: Print ansible_facts (for debug only)
  debug:
    var: ansible_facts

- name: Print mac_address per host
  debug:
    var: mac_address

- name: Collect all MAC addresses into mac_list
  set_fact:
    mac_list: "{{ groups['all'] | map('extract', hostvars, 'mac_address') | list }}"
  delegate_to: localhost

- name: Fail if duplicate MAC addresses exist
  fail:
    msg: "Duplicate MAC addresses detected: {{ mac_list }}"
  when: mac_list | length != (mac_list | unique | length)