- name: Check duplicated mac address
  import_tasks: mac_addresses_check.yaml

- name: Set common netowork setting
  import_tasks: common.yaml

- name: Set control planes network
  when: "'control_planes' in group_names"
  import_tasks: controlplane-network-setting.yaml

- name: Set data plane network
  when: "'worker_nodes' in group_names"
  import_tasks: dataplane-network-setting.yaml