- hosts: all
  become: yes
  roles:
    - common

- hosts: control_planes
  become: yes
  roles:
    - network
    - containerd
    - kubernetes
    - kubeadm

- hosts: worker_nodes
  become: yes
  roles:
    - network
    - containerd
    - kubernetes
    - kubeadm