- name: Initialize Kubernetes Control Plane
  hosts: control_planes
  become: true
  tasks:
    - name: Run kubeadm init
      command: >
        kubeadm init
        --apiserver-advertise-address=192.168.56.10
        --control-plane-endpoint=cp1.cluster.local
        --pod-network-cidr=10.244.0.0/16
        --upload-certs
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create .kube directory
      file:
        path: /root/.kube
        state: directory
        mode: '0755'

    - name: Copy admin.conf to kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root
        group: root
        mode: '0644'

    - name: Extract kubeadm join command with cert key (for other CPs and workers)
      command: kubeadm token create --print-join-command
      register: join_cmd

    - name: Save join command
      set_fact:
        kubeadm_join_command: "{{ join_cmd.stdout }}"

- name: Join worker nodes to cluster
  hosts: worker_nodes
  become: true
  tasks:
    - name: Run kubeadm join
      command: "{{ hostvars['cp']['kubeadm_join_command'] }}"
      args:
        creates: /etc/kubernetes/kubelet.conf

- name: Install CNI Calico
  hosts: control_planes
  become: true
  tasks:
    - name: Download Calico manifest
      get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.30.2/manifests/calico.yaml
        dest: /tmp/calico.yaml
        mode: '0644'

    - name: Apply Calico manifest using kubectl
      command: kubectl apply -f /tmp/calico.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf